"use client";
import "./globals.css";
import { Saira } from "next/font/google";
import Nav from "./Nav";
import ShoContextProvider from "@/contexts/ShopContext";

const inter = Saira({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <ShoContextProvider>
          <Nav />
          <div className="max-w-screen-lg m-auto">{children}</div>
        </ShoContextProvider>
      </body>
    </html>
  );
}
